### ISSUE TITLE
watermark not knitting to pdf

### ISSUE THREAD

**Issue by mjfrigaard** [hebrewseniorlife/memor#13]
# `memor` issue (R package) 

Thank you so much for creating such an excellent package :) I use it often. 

I received an error message that I couldn't debug. I've also created a [Github repo](https://github.com/mjfrigaard/watermark-issue) with the files for reference. 

## Error 

With the following `memor-profile.yaml`,

```yaml
company:
  name: First Name
  address: Somewhere, US
  phone: 1+555.555.5555
  email: person@gmail.com
confidential: false
watermark: NOTES
footer_on_first_page: true
toc: true
lot: false
lof: false
number_sections: false
latex_engine: xelatex
```

I get the following error when I try to knit the [`memor-watermark-error.Rmd` file](https://github.com/mjfrigaard/watermark-issue/blob/main/memor-watermark-error.Rmd).

```r
! Extra \endgroup.
\document ->\endgroup 
                      \let \BeforeStartOfDocument \@firstofone \cpt@beforest...
l.292 \begin{document}

Error: LaTeX failed to compile memor-watermark-error.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See memor-watermark-error.log for more info.
Execution halted
```

The entire .log and .tex files for the error are [here](https://github.com/mjfrigaard/watermark-issue/tree/main/error-logs), but I can't seem to find the source of the error. 

## Workaround 

However, when I removed the `watermark` parameter, I was able to create the [output .pdf](https://github.com/mjfrigaard/watermark-issue/blob/main/memor-watermark-error.pdf)

```yaml
company:
  name: First Name
  address: Somewhere, US
  phone: 1+555.555.5555
  email: person@gmail.com
confidential: false
footer_on_first_page: true
toc: true
lot: false
lof: false
number_sections: false
latex_engine: xelatex
```

The accompanying .log file for this output is [here](https://github.com/mjfrigaard/watermark-issue/blob/main/memor-watermark-error.log)

Any help would be greatly appreciated.
