### ISSUE TITLE
Subtitle missing

### ISSUE THREAD

**Issue by bearloga** [hebrewseniorlife/memor#4]
Well this is weird! Even though [memor.tex includes a bit about including subtitles](https://github.com/hebrewseniorlife/memor/blob/420e5ee31b1fb5a6f64c7fb01f2292f60f10dd02/inst/rmarkdown/templates/memor/resources/memor.tex#L143-L148), for some reason they don't make it into the output.

```YAML
---
title: "Title"
subtitle: "Subtitle"
author: 
- You Name
- Second Author
date: "`r Sys.Date()`"
output: memor::pdf_memo
---

Text.
```

![Example of missing subtitle](https://user-images.githubusercontent.com/1807519/42395289-39dcb4d0-8112-11e8-87a1-67dbe886f2c3.png)
